### PR TITLE
docs: Improved cURL snippets

### PR DESCRIPTION
**Pull request by Anush008**
## [PREVIEW](https://qdrant-preview-275f5737-6afb-40e1-aebb-7039997bd812.docs.buildwithfern.com/)

I have tested the examples.

### NOTE

- The `fern/apis` files are auto-generated.

### CODE REVIEW

**Comment by davidmyriel** [comment]
Looks good, so this is a permanent override?

**Comment by Anush008** [comment]
> Looks good, so this is a permanent override?

I didn't get it.

**Comment by Anush008** [comment]
@davidmyriel, @mrscoopers Good to merge?

**Comment by mrscoopers** [comment]
Should we worry about examples of search where limit > 1, but we show POST with one example, or it's intuitive? I don't have an opinion here

**Comment by Anush008** [comment]
>  but we show POST with one example,

Do you mean a response with 1 result?

**Comment by Anush008** [comment]
I just tried to set the limit to 1 in all the snippets.
But I think that won't look right either. Since we usually do the top few results.
So I propose to keep it as is.

**Comment by mrscoopers** [comment]
Okay, then lgtm, thank you for such a hard work!

**Pull request merged**
